---
steps:
- name: gcr.io/$PROJECT_ID/gcp-devops:${_IMAGE_VERSION}
  id: tf-fmt
  entrypoint: terraform
  dir: deployments/dev
  args:
  - fmt
  - -recursive
  - -check
- name: gcr.io/$PROJECT_ID/gcp-devops:${_IMAGE_VERSION}
  id: tf-plan
  entrypoint: bash
  env:
    - "TF_VAR_project=$PROJECT_ID"
  dir: deployments/dev
  args:
    - '-c'
    - |
      terraform init
      terraform plan -out=terraform.tfplan
      terraform show -json terraform.tfplan > terraform.tfplan.json
- name: gcr.io/$PROJECT_ID/gcp-devops:${_IMAGE_VERSION}
  id: tf-validator
  entrypoint: terraform-validator
  dir: deployments/dev
  args:
  - validate
  - terraform.tfplan.json
  - --policy-path=../../policy-library/
  - --project
  - $PROJECT_ID
options:
  env:
  - "TF_IN_AUTOMATION=1"
  - "TF_CLI_ARGS_init=-input=false"
  - "TF_CLI_ARGS_plan=-input=false"

substitutions:
  _IMAGE_VERSION: "0.12.29"
